# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29af40df17f79dcc81c34326d84e1790c242166b9f52de8c15325ba0f82f5df9143a50f47878cc129e86294b45cfc4a43177260bccd3d9ca6057a5ba26dac2d4

test:
  secret_key_base: edf28d72741e657689f9d25098755ca428552dbec0ff3b65349fc7549af1e4c26b2ad01a47ec70976700e937a8dab5e38ec59dab60091af06479cde3d053cc26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
